version: "3"

services:
  db-simanja:
    image: postgres:15
    volumes:
      - "./db-simanja:/var/lib/postgresql/data"
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=simanjadb
      - POSTGRES_USER=simanja
      - POSTGRES_PASSWORD=simanja123
